---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

```{r}
data("rest_inspec")

rest_inspec_df = 
  rest_inspec %>% 
  janitor::clean_names() %>% 
  select(boro, cuisine_description, dba, inspection_date, action, violation_description, critical_flag, score, grade) %>% 
  filter(
    cuisine_description %in% c("Pizza", "Delicatessen", "Hotdogs",  "Bagels/Pretzels", "Donuts")
  ) %>% 
  drop_na(grade)

```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart 1

```{r}
rest_inspec_df %>% 
  mutate(
    cuisine_description = fct_reorder(cuisine_description, score)
  ) %>% 
  plot_ly(
    x = ~cuisine_description, y = ~score, type = "box", color = ~cuisine_description, colors = "viridis"
  )
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart 2

```{r}
rest_inspec_df %>% 
  count(cuisine_description) %>% 
  mutate(
    cuisine_description = fct_reorder(cuisine_description, n)
  ) %>% 
  plot_ly(x = ~cuisine_description, y = ~n, color = ~cuisine_description, type = "bar", colors = "viridis")
```

### Chart 3

```{r}
rest_inspec_df %>% 
  filter(
    boro == "MANHATTAN"
  ) %>% 
  plot_ly(x = ~inspection_date, y = ~score, color = ~cuisine_description, type = "scatter", colors = "viridis")
